scheduler:
  cron_pattern: "54 * * * *"
  workers_count: 1
  logger:
    loglvl: debug
    mode: development
    encoding: json
  scraper:
    output_every: 10000
    max_depth: 5
    filter_pattern: "^[A-Za-zА-Яа-яЁё]+$"
    tags_to_parse: ["div", "span", "p", "a", "h1", "h2", "h3", "h4", "h5", "h6"]
    is_async: false
    # async_delay: 3s
    # async_request_limit: 5
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      Accept-Language: "en-US,en;q=0.9"
      Accept-Encoding: "gzip, deflate, br, zstd"
      Connection: "keep-alive"
    queue:
      enabled: false
      thread_number: 2
      max_size: 250000
  sites:
    # - name: coursera
    #   url: https://www.coursera.org
    - name: go.dev
      url: https://pkg.go.dev

kafka:
  max_retry: 5
  brokers:
    - kafka:9093
  topics:
    scraper_data: "scraper_data"
